### ISSUE TITLE
Set up ORM for categories (shopping, food....)

### ISSUE THREAD

**Issue by SamEThibault** [SamEThibault/shacks-2022#4]
The way it will be structured:
{"food": ['Tim Hortons', 'McDonalds'], "groceries": ['Winners"]...}

**Comment by LoganHoogendijk** [comment]
Isn't it easier if there was a dict that was like categories = {"food": ['Tim Hortons', 'McDonalds'], "groceries": ['Winners"]}

**Comment by SamEThibault** [comment]
> Isn't it easier if there was a dict that was like categories = {"food": ['Tim Hortons', 'McDonalds'], "groceries": ['Winners"]}

True, that's gonna be the better approach for testing since the database will be local. I'll edit the comment ty!
